spring.application.name=script-site
spring.datasource.url=jdbc:h2:mem:gov
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=Welcome1

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

oauth2.discord.authorization-uri=https://discord.com/oauth2/authorize
oauth2.discord.token-uri=https://discord.com/api/oauth2/token
oauth2.discord.user-info-uri=https://discord.com/api/users/@me
oauth2.discord.user-name-attribute=username

oauth2.discord.client-name=discord
oauth2.discord.authorization-grant-type=authorization_token
oauth2.discord.client-id=1550560437396054046
oauth2.discord.client-secret=vbcSPNRtlowEEIbYQe41fRYtYJQzrI2J
oauth2.discord.scope=identify, email
oauth2.discord.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE

spring.data.web.pageable.serialization-mode=via_dto