spring.application.name=script-site
spring.datasource.url=jdbc:h2:mem:gov
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=Welcome1

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true